FIREBASE_API_KEY="AIzaSyBFO0ntX7NEstf4Lq-P5Mrp_eF6R261AYE"
FIREBASE_AUTH_DOMAIN="student-placement-predic-7c846.firebaseapp.com"
FIREBASE_PROJECT_ID="student-placement-predic-7c846"
FIREBASE_STORAGE_BUCKET="student-placement-predic-7c846.firebasestorage.app"
FIREBASE_MESSAGING_SENDER_ID="256799812053"
FIREBASE_APP_ID="1:256799812053:web:c0305982c92a051defb55c"